name: Trigger Cloud Build for Node.js App


on: [workflow_dispatch]


permissions:
  id-token: write
  contents: read

  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: us-central1
      SERVICE_NAME: nodejs-cloudrun-service
      IMAGE: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nodejs-ar/nodejs-app:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        id: auth
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/774388061268/locations/global/workloadIdentityPools/gha-gcp/providers/github-provider'
          service_account: '774388061268-compute@developer.gserviceaccount.com'
          project_id: ${{ env.PROJECT_ID }}

        
      # - name: Trigger Cloud Build
      #   # run: |
      #     gcloud builds submit --config=cloudbuild.yaml .
        
            
      



